services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_SSLMODE: disable
    volumes:
      - image_storage:/app/storage
    networks:
      - app-network

volumes:
  image_storage:
    name: personal-image-storage

networks:
  app-network:
    external: true
